### PR TITLE
Support using custom logger

### PR DESCRIPTION
**Pull request by ejhayes**
Custom logger is not currently supported when BullModule is loaded initially. Switching to use an instance of the logger function `private readonly logger = new Logger(...)` allows logging to work in the event that a custom logger is specified, for example:

```
const app = await NestFactory.create(AppModule, {
    logger:  new MyCustomLogger(),
});
```

The only place that I couldn't seem to figure out is the `Logger.warn` call in `bull.decorator.ts`...custom logger appears to be working everywhere else though!

Thanks again for this module @anchan828

### CODE REVIEW

**Comment by anchan828** [comment]
Hi, @ejhayes 
Thank you for your PR! It looks good.
I merge your PR and will publish new version

**Comment by anchan828** [comment]
Some tests failed... in #79 
I will fix them.

**Comment by ejhayes** [comment]
Ah yikes...I was having some issues getting the tests to pass locally @anchan828 --thanks for fixing!

**Comment by anchan828** [comment]
Published 0.3.9
Thanks @ejhayes!

**Pull request merged**
